Remove every other element
MIT-Emerging-Talent/ET6-foundations-group-30 pull request #40
Opened 2024-12-30 14:36 UTC by mojtabafayyaz

---
name: solution review 
about: A template PR for code review with a checklist
---

# Behavior

## Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2025-01-02 20:38 UTC, MadiMalik commented on .vscode/extensions.json
why did you make this change?

2025-01-02 20:39 UTC, MadiMalik commented on .vscode/settings.json
Can you explain these changes?

2025-01-02 21:09 UTC, MadiMalik requested changes
Hey Mojtaba,
Your code is good, but there’s room for improvement. You could add more test cases to check the function’s behavior with an empty list as a boundary case and how it handles duplicate values. Also please explain the changes you made in .vscode/extensions.json file

2025-01-03 12:52 UTC, mojtabafayyaz commented
> Hey Mojtaba, Your code is good, but there’s room for improvement. You could add more test cases to check the function’s behavior with an empty list as a boundary case and how it handles duplicate values. Also please explain the changes you made in .vscode/extensions.json file

### Hi Madiha,

Thank you so much for your valuable feedback!

### Test Case Updates:
1. **Boundary Case for Empty List:**
   - I've added a test case to handle the empty list scenario, ensuring that the function behaves as expected even when no elements are present.

2. **Handling Duplicate Values:**
   - I’ve also added a test case to check how the function behaves with duplicate values. This helps confirm that the function correctly removes every second element, including duplicates, without any unexpected behavior.

### Regarding `.vscode/extensions.json`:
- The changes to the `.vscode/extensions.json` file were included mistakenly in my earlier commit. I’ve since cleaned them up and made sure they’re removed from the pull request before submission. I apologize for the oversight and confusion.

Thank you again for your helpful comments, and please feel free to let me know if there’s anything else I can improve.

Best regards,  
Mojtaba

2025-01-03 17:02 UTC, MadiMalik requested changes
please add a module docstring to the test file as well

2025-01-03 17:02 UTC, MadiMalik commented
Thank you for cleaning up the .vscode/extensions.json file and adding additional test cases to your test file. I have one more suggestion: could you please add a module docstring to the test file as well? It’s one of the requirements mentioned in the list.

2025-01-03 18:07 UTC, mojtabafayyaz commented
> please add a module docstring to the test file as well

Dear Madiha,  I just added a module docstring to the test file.

2025-01-03 20:44 UTC, MadiMalik approved these changes
Thanks for the docstring, Mojtaba

2025-01-03 20:44 UTC, MadiMalik approved these changes

2025-01-03 20:45 UTC, MadiMalik approved these changes

2025-01-03 20:45 UTC, MadiMalik approved these changes

2025-01-03 20:45 UTC, MadiMalik approved these changes

2025-01-03 20:46 UTC, MadiMalik approved these changes

2025-01-03 20:46 UTC, MadiMalik approved these changes

2025-01-03 20:47 UTC, MadiMalik approved these changes

2025-01-03 20:49 UTC, MadiMalik approved these changes
thanks for adding docstring

2025-01-03 20:50 UTC, MadiMalik approved these changes

2025-01-03 20:50 UTC, MadiMalik approved these changes

2025-01-03 20:50 UTC, MadiMalik approved these changes

2025-01-03 20:52 UTC, MadiMalik approved these changes

2025-01-03 20:57 UTC, merged